name: Build and Package Next.js Application

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Run build packager script
        shell: pwsh
        run: |
          # Set execution policy
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          
          # Run the packager script from builder folder
          $scriptPath = ".\builder\build-packager.ps1"
          
          Write-Host "Running packager script: $scriptPath"
          Write-Host "Output path: dist"
          
          & $scriptPath -OutputPath "dist" -SkipBuild $false -OpenFolder $false
          
          Write-Host "Packager script completed successfully"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: orbis-app-build-${{ github.run_number }}
          path: dist/
          retention-days: 30

      - name: Create GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
