name: Build Next.js Application

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  release:
    types: [created, published]
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  id-token: write
  packages: write
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Get version from package.json
        id: get_version
        shell: pwsh
        run: |
          $packageJson = Get-Content "package.json" | ConvertFrom-Json
          $version = $packageJson.version
          Write-Output "VERSION=$version" >> $env:GITHUB_ENV
          Write-Output "Package version: $version"

      - name: Create build archive
        shell: pwsh
        run: |
          $archiveName = "orbis-${{ env.VERSION }}.zip"
          
          # Create a temporary directory for the package
          $packageDir = "package"
          New-Item -ItemType Directory -Force -Path $packageDir
          
          # Copy the essential application folders
          
          # 1. Copy .next/standalone directory (the main application)
          if (Test-Path ".next/standalone") {
            Copy-Item -Path ".next/standalone" -Destination "$packageDir/.next/standalone" -Recurse -Force
            Write-Output "Copied .next/standalone directory"
          }
          
          # 2. Copy .next/static directory (static assets)
          if (Test-Path ".next/static") {
            Copy-Item -Path ".next/static" -Destination "$packageDir/.next/static" -Recurse -Force
            Write-Output "Copied .next/static directory"
          }
          
          # 3. Copy public directory (static assets)
          if (Test-Path "public") {
            Copy-Item -Path "public" -Destination "$packageDir/public" -Recurse -Force
            Write-Output "Copied public directory"
          }
          
          # Copy deployment scripts from builder directory
          
          # 4. Copy run.bat (application launcher)
          if (Test-Path "builder/run.bat") {
            Copy-Item -Path "builder/run.bat" -Destination "$packageDir/run.bat" -Force
            Write-Output "Copied run.bat"
          }
          
          # 5. Copy setup.ps1 (environment setup script)
          if (Test-Path "builder/setup.ps1") {
            Copy-Item -Path "builder/setup.ps1" -Destination "$packageDir/setup.ps1" -Force
            Write-Output "Copied setup.ps1"
          }
          
          # Create version.json file with build information
          $versionInfo = @{
            name = "orbis-ship"
            version = "${{ env.VERSION }}"
            buildDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC"
            buildCommit = "${{ github.sha }}"
            buildBranch = "${{ github.ref_name }}"
            buildNumber = "${{ github.run_number }}"
            platform = "windows"
            runtime = "node-standalone"
            size = "~18MB"
          } | ConvertTo-Json -Depth 2
          
          $versionInfo | Out-File -FilePath "$packageDir/version.json" -Encoding UTF8
          Write-Output "Created version.json"
          
          # Create a README for deployment
          $readmeLines = @(
            "# Orbis Ship Application - v${{ env.VERSION }}",
            "",
            "This package contains the complete Orbis Ship application ready for deployment.",
            "",
            "## Quick Start",
            "",
            "1. Setup Environment (Run as Administrator):",
            "   .\setup.ps1",
            "",
            "2. Start Application:",
            "   .\run.bat",
            "",
            "## Package Contents",
            "",
            "- .next/ - Next.js application build",
            "  - standalone/ - Complete standalone application", 
            "  - static/ - Static assets and chunks",
            "- public/ - Public static files",
            "- run.bat - Application launcher script",
            "- setup.ps1 - Environment setup script", 
            "- version.json - Build and version information",
            "- README.md - This file",
            "",
            "## System Requirements",
            "",
            "- Windows 10/11 or Windows Server 2016+",
            "- No Node.js installation required (standalone build)",
            "- PowerShell 5.1+ (for setup script)",
            "",
            "## Build Information",
            "",
            "- Version: ${{ env.VERSION }}",
            "- Built: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')",
            "- Commit: ${{ github.sha }}",
            "- Branch: ${{ github.ref_name }}",
            "",
            "---",
            "Built with ❤️ using GitHub Actions"
          )
          
          $readmeLines | Out-File -FilePath "$packageDir/README.md" -Encoding UTF8
          Write-Output "Created README.md"
          
          # Show package contents
          Write-Output "Package contents:"
          Get-ChildItem $packageDir -Recurse -Name | Sort-Object | ForEach-Object { Write-Output "  $_" }
          
          # Create ZIP from the package directory
          Compress-Archive -Path "$packageDir/*" -DestinationPath $archiveName -Force
          
          # Clean up
          Remove-Item $packageDir -Recurse -Force
          
          Write-Output "Created build archive: $archiveName with only essential folders"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: orbis-${{ env.VERSION }}
          path: orbis-${{ env.VERSION }}.zip
          retention-days: 30

      - name: Create Release using GitHub CLI
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        shell: pwsh
        run: |
          # Set up GitHub CLI authentication
          $env:GH_TOKEN = "${{ secrets.GITHUB_TOKEN }}"
          
          # Check if release already exists
          $releaseExists = $false
          try {
            gh release view "latest" --repo "${{ github.repository }}" | Out-Null
            $releaseExists = $true
            Write-Output "Release 'latest' already exists, will update it"
          } catch {
            Write-Output "Release 'latest' does not exist, will create it"
          }
          
          if ($releaseExists) {
            # Delete existing release
            gh release delete "latest" --repo "${{ github.repository }}" --yes
            Write-Output "Deleted existing 'latest' release"
          }
          
          # Create new release
          gh release create "latest" "orbis-${{ env.VERSION }}.zip" `
            --repo "${{ github.repository }}" `
            --title "Orbis Ship Latest (v${{ env.VERSION }})" `
            --notes "## Orbis Ship Latest Development Build

          **🔄 Automatically updated from main branch**
          **Version:** v${{ env.VERSION }}
          **Built from commit:** ${{ github.sha }}
          **Build date:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')

          This is the latest development build from the main branch.

          ### 📦 What's included:
          - Complete Next.js standalone application
          - Public static assets  
          - Ready for deployment on Windows machines

          ### 🚀 Installation:
          1. Download the orbis-${{ env.VERSION }}.zip file
          2. Extract to your desired location
          3. Run the extracted application

          ---
          Built with ❤️ using GitHub Actions" `
            --latest

          Write-Output "Successfully created release 'latest'"

      - name: Create Tagged Release using GitHub CLI  
        if: startsWith(github.ref, 'refs/tags/v')
        shell: pwsh
        run: |
          # Set up GitHub CLI authentication
          $env:GH_TOKEN = "${{ secrets.GITHUB_TOKEN }}"
          
          # Create release for the tag
          gh release create "${{ github.ref_name }}" "orbis-${{ env.VERSION }}.zip" `
            --repo "${{ github.repository }}" `
            --title "Orbis Ship v${{ env.VERSION }}" `
            --notes "## Orbis Ship Release v${{ env.VERSION }}

          **Built from commit:** ${{ github.sha }}
          **Build date:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')

          ### 📦 What's included:
          - Complete Next.js standalone application
          - Public static assets
          - Ready for deployment on Windows machines

          ### 🚀 Installation:
          1. Download the orbis-${{ env.VERSION }}.zip file
          2. Extract to your desired location  
          3. Run the extracted application

          ### 📊 Package Info:
          - **Size:** ~18MB
          - **Runtime:** Node.js (standalone, no installation required)
          - **Platform:** Windows

          ---
          Built with ❤️ using GitHub Actions"

          Write-Output "Successfully created tagged release '${{ github.ref_name }}'"
